
openapi: 3.0.0
info:
  title: Blog app api
  description: This is a sample project with Node.js, express, MySql2, Sequelize
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Localhost
